import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Dockbar from "@/components/Dockbar";

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ['400', '700'],
  style: 'normal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} antialiased`}
      >
        <Navbar />

        {children}

        <Dockbar />
      </body>
    </html>
  );
}
